---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
        * Incredibly awesome content
    media:
      - ebooks
    price: 3500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        * Includes 10 hours of video screencasts
        * Ebooks inclded in PDF/EPUB/MOBI formats
    media:
      - ebooks
      - media/screencasts
    price: 12500

authors:
  -
    name: "Michael Hartl"
    image: /images/2011_michael_hartl.png
    bio:
      |
        Michael Hartl is the author of the
        [Ruby on Rails Tutorial](http://railstutorial.org)
        and is a cofounder of [Softcover](http://softcover.io).

faq:
  -
    question: What is Softcover?
    answer: Softcover is a publishing platform for technical authors.
            It combines an open-source ebook production system with an integrated
            sales platform.

  -
    question: How do I use Softcover?
    answer: Go to <http://www.softcover.io/> to sign up for an account and
            then follow the instructions on the setup page.

testimonials:
  -
    name: Mark Bates
    title: Author, Conquering the Command Line
    image: /images/mark_bates.jpg
    text: I have never used tools as good as these for writing a book before!
          The Softcover platform just got out of my way and let me focus on writing.


marketing_content: ''

contact_email: 'michael@softcover.io'
hide_custom_domain_footer: false
