---
slug: example_book
filename: example_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 0fbf464b-c663-41a4-87d9-41fdcc2330e4
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
